# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_to_map <- function(mat, type = 1L, n_actors = 10L) {
    .Call(`_ergm_sign_mat_to_map`, mat, type, n_actors)
}

trying_out <- function(network, n_actors = 10L) {
    .Call(`_ergm_sign_trying_out`, network, n_actors)
}

set_seed <- function(seed) {
    invisible(.Call(`_ergm_sign_set_seed`, seed))
}

simulate_numbers <- function(min = 0L, max = 10L, number = 100L) {
    .Call(`_ergm_sign_simulate_numbers`, min, max, number)
}

#' Count the number of dyadwise shared partners
#' 
#' This function returns for each dyad the number of shared positive partners.
#'
NULL

#' Count the number of positive edgewise shared partners
#' 
#' This function returns for each dyad the number of shared positive partners.
#'
#' @param network A matrix of the adjacency matrix of a signed network. 
#' @param n_actors A numeric value of the number of actors in the network. 
#' @param n_edges A numeric value of the number of edges in the network. 
NULL

#' Count the number of edgewise shared enemies
#' 
#' This function returns for each edge the number of shared enemies.
#'
#' @param network A matrix of the adjacency matrix of a signed network. 
#' @param n_actors A numeric value of the number of actors in the network. 
#' @param n_edges A numeric value of the number of edges in the network. 
NULL

arma_sample <- function(n, k, prob) {
    .Call(`_ergm_sign_arma_sample`, n, k, prob)
}

sample_signed <- function(n, prob) {
    .Call(`_ergm_sign_sample_signed`, n, prob)
}

simulate_networks_new <- function(coefs, terms, n_actors, data_list, type_list, mh, n_proposals = 100L, n_proposals_burn_in = 100L, seed = 123L, number_networks = 1L, only_stats = FALSE) {
    .Call(`_ergm_sign_simulate_networks_new`, coefs, terms, n_actors, data_list, type_list, mh, n_proposals, n_proposals_burn_in, seed, number_networks, only_stats)
}

simulate_networks_stats <- function(coefs, terms, n_actors, data_list, type_list, mh, n_proposals = 100L, n_proposals_burn_in = 100L, seed = 123L, number_networks = 1L) {
    .Call(`_ergm_sign_simulate_networks_stats`, coefs, terms, n_actors, data_list, type_list, mh, n_proposals, n_proposals_burn_in, seed, number_networks)
}

simulate_trying <- function(coefs, terms, n_actors, data_list, type_list, n_proposals = 100L, n_proposals_burn_in = 100L, seed = 123L, number_networks = 1L, only_stats = FALSE) {
    .Call(`_ergm_sign_simulate_trying`, coefs, terms, n_actors, data_list, type_list, n_proposals, n_proposals_burn_in, seed, number_networks, only_stats)
}

count_global <- function(network, terms, n_actors, data_list, type_list) {
    .Call(`_ergm_sign_count_global`, network, terms, n_actors, data_list, type_list)
}

trying_again2 <- function(network, terms, n_actors, data_list, type_list, from, to, change) {
    .Call(`_ergm_sign_trying_again2`, network, terms, n_actors, data_list, type_list, from, to, change)
}

simulation_mat <- function(network, terms, n_actors, n_proposals, seed, number_networks, data_list, type_list, coef, mh) {
    .Call(`_ergm_sign_simulation_mat`, network, terms, n_actors, n_proposals, seed, number_networks, data_list, type_list, coef, mh)
}

count_global_terms <- function(network, terms, n_actors, data_list, type_list) {
    .Call(`_ergm_sign_count_global_terms`, network, terms, n_actors, data_list, type_list)
}

mle_estimation <- function(network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, beg_coef, mh, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_mle_estimation`, network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, beg_coef, mh, max_it, tol, start_with_empty_net)
}

mle_estimation_stepping <- function(network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, beg_coef, steps, mh, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_mle_estimation_stepping`, network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, beg_coef, steps, mh, max_it, tol, start_with_empty_net)
}

t_mle_estimation_stepping <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, steps, mh, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_mle_estimation_stepping`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, steps, mh, max_it, tol, start_with_empty_net)
}

t_mle_estimation_stepping_p <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, steps, mh, cluster, data_lists_par, networks_par, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_mle_estimation_stepping_p`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, steps, mh, cluster, data_lists_par, networks_par, max_it, tol, start_with_empty_net)
}

t_mle_estimation_p <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, mh, cluster, data_lists_par, networks_par, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_mle_estimation_p`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, mh, cluster, data_lists_par, networks_par, max_it, tol, start_with_empty_net)
}

t_mle_estimation <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, mh, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_mle_estimation`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, mh, max_it, tol, start_with_empty_net)
}

t_est_var_p <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, coef, mh, cluster, data_lists_par, networks_par, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_est_var_p`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, coef, mh, cluster, data_lists_par, networks_par, start_with_empty_net)
}

t_est_var <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, coef, mh, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_est_var`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, coef, mh, start_with_empty_net)
}

t_rm_mle_estimation <- function(networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, mh, D, c, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_t_rm_mle_estimation`, networks, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_lists, type_list, beg_coef, mh, D, c, max_it, tol, start_with_empty_net)
}

est_var <- function(network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, coef, mh, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_est_var`, network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, coef, mh, start_with_empty_net)
}

rm_mle_estimation <- function(network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, beg_coef, mh, D, c, max_it = 10L, tol = 0.001, start_with_empty_net = TRUE) {
    .Call(`_ergm_sign_rm_mle_estimation`, network, terms, n_actors, n_proposals, n_proposals_burn_in, seed, number_networks, data_list, type_list, beg_coef, mh, D, c, max_it, tol, start_with_empty_net)
}

preprocess_pseudo_lh_new <- function(network, n_actors, terms, data_list, type_list) {
    .Call(`_ergm_sign_preprocess_pseudo_lh_new`, network, n_actors, terms, data_list, type_list)
}

count_dyadwise_shared_partner_pos <- function(network, n_actors) {
    .Call(`_ergm_sign_count_dyadwise_shared_partner_pos`, network, n_actors)
}

count_edgewise_shared_partner_pos <- function(network, n_actors, n_edges) {
    .Call(`_ergm_sign_count_edgewise_shared_partner_pos`, network, n_actors, n_edges)
}

count_edgewise_shared_enemies <- function(network, n_actors, n_edges) {
    .Call(`_ergm_sign_count_edgewise_shared_enemies`, network, n_actors, n_edges)
}

